config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :skills do
    resources :bookings
  end
  resources :bookings do
    member do
      patch :confirm
    end
  end
  get '/dashboard', to: 'pages#dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :skill

  validates :start_date, :end_date, presence: true
  validate :end_date_after_start_date

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
 end
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :bookings, dependent: :destroy

  include PgSearch::Model
  pg_search_scope :search_skill,
    against: [ :name ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :photo
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :skills
  has_many :bookings
  has_many :bookings_as_owner, through: :skills, source: :bookings

  #validates :name, presence: true
  #validates :description, presence: true
  #validates :region, presence: true
  #validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :description, :region])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :description, :region])
  end
  
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @skill = Skill.find(params[:skill_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @skill = Skill.find(params[:skill_id])
    @booking.user = current_user
    @booking.skill = @skill
    if @booking.save
      #redirect_to skill_path(@skill)
      redirect_to dashboard_path(@skill)
    else
      render :new
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    redirect_to booking_path(@booking)
  end

  def confirm
    @booking = Booking.find(params[:id])
    @booking.confirmed = true
    @booking.save
    redirect_to dashboard_path
  end

  private

  def find_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :confirmed)
  end
end

app/controllers/my_skills_controller.rb
class MySkillsController < ApplicationController
  def index
    @skills = current_user.skills
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end

  def dashboard
    @skills = current_user.skills
    @bookings = current_user.bookings
    @bookings_as_owner = current_user.bookings_as_owner

  end

  # def booking_confirmed

  #   @bookings = bookings.where(confirmed: true)
  # end

  # def booking_waiting
  #   @bookings = current_user.bookings
  #   @bookings = bookings.where(confirmed: false)
  # end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    if params[:query].present?
      @skills = Skill.search_skill(params[:query])
    else
      @skills = Skill.all
    end
  end

  def show
    @skill = Skill.find(params[:id])
  end

  def new
    @skill = Skill.new
  end

  def create
    @skill = Skill.new(skill_params)
    @skill.user = current_user
    if @skill.save
      redirect_to skill_path(@skill)
    else
      render :new
    end
  end

  def edit
    @skill = Skill.find(params[:id])
  end

  def update
    @skill = Skill.find(params[:id])
    @skill.update(skill_params)
    redirect_to skill_path(@skill)
  end

  private

  def find_skill
    @skill = skill.find(params[:id])
  end

  def skill_params
    params.require(:skill).permit(:name, :photo, :unit_price, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div class="container">
  <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
    <h2>Select your date</h2>

    <%= simple_form_for([@skill, @booking]) do |f| %>
      <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.button :submit, "Book", class: "btn btn-primary" %>
      <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<%= render "form", booking: @booking %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentArtisan</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
<div class="main">
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <p class="notice"><%= notice %></p>

    <%= yield %>

  </body>
 </div>
  <footer>


  <p class="alert"><%= alert %></p>
   <%= render 'shared/footer' %>
  </footer>
</html>

app/views/my_skills/index.html.erb
<div class="container text-center">

  <h1> Vos services</h1>
    <% @skills.each do |skill|%>
    <div class="cards">
      <%= skill.name%>
    <%end%>
  </div>
</div>

app/views/pages/dashboard.html.erb
<div class="container text-center">
  <h1>Dashboard</h1>

  <!-- Partie pour les users -->
  <h2> Your bookings </h2>
  <% if @bookings.nil? %>
    <p> You have no booking </p>
  <% else %>
    <p>You currently have <%= @bookings.count%> booking waiting : </p>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Skill</th>
          <th scope="col">Start Date</th>
          <th scope="col">End Date</th>
          <th scope="col">Price per day</th>
          <th scope="col">Total Pricing</th>
          <th scope="col">Contact Craftsman</th>
        </tr>
      </thead>
      <tbody>
      <% counter = 0 %>
        <% @bookings.each do |booking|%>
          <% color_class = booking.confirmed ? "text-success" : "text-danger" %>
          <tr class="<%= color_class %>">
            <th scope="col"><%= counter += 1 %></th>
            <th scope="col"><%= booking.skill.name%></th>
            <th scope="col"><%= booking.start_date%></th>
            <th scope="col"><%= booking.end_date%></th>
            <th scope="col"><%= booking.skill.unit_price%></th>
            <th scope="col"><%= (((booking.end_date - booking.start_date)+ 1)*booking.skill.unit_price).to_i %>€</th>
            <th scope="col"><%= booking.skill.user.name%></th>
          </tr>
        <%end%>
      </tbody>
    </table>
  <% end %>



  <!-- partie pour les artisans -->
  <h2>Craftsman</h2>
  <% if @skills.nil? %>
    <%= link_to "Propose your skills", new_skill_path %>
    <p>Propose your skills</p>
  <% else %>
    <p>Manage your bookings</p>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Skill</th>
          <th scope="col">Start Date</th>
          <th scope="col">End Date</th>
          <th scope="col">Price per day</th>
          <th scope="col">Total Pricing</th>
          <th scope="col">Confirmation</th>
        </tr>
      </thead>
      <tbody>
        <% counter = 0 %>
        <% @bookings_as_owner.each do |booking|%>
          <% color_class = booking.confirmed ? "text-success" : "text-warning" %>
          <tr class="<%= color_class %>">
            <% duration = (booking.end_date - booking.start_date).to_i %>
            <th scope="col"><%= counter += 1 %></th>
            <th scope="col"><%= booking.skill.name%></th>
            <th scope="col"><%= booking.start_date%></th>
            <th scope="col"><%= booking.end_date%></th>
            <th scope="col"><%= booking.skill.unit_price%></th>
            <th scope="col"><%= (((booking.end_date - booking.start_date)+ 1)*booking.skill.unit_price).to_i %>€</th>
            <th scope="col">
              <% if booking.confirmed  %>
                Confirmed
              <% else %>
                <%= link_to "Confirm",  confirm_booking_path(booking), method: :patch %>
              <% end %>
            </th>
          </tr>
        <%end%>
      </tbody>
    </table>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="banner">
  <div class="container-xl">
    <div class="background-content">

        <h1>Do it yourself or ... RentArtisan !</h1>
        <br>
        <%= form_tag skills_path, method: :get do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control col-9",
            placeholder: "Enter here the skill you are looking for"
          %>
          <%= submit_tag "See results", class: "btn btn-flat" %>
        <% end %>
    </div>
  </div>
</div>


<div class="home-text container-fluid bg-light p-9 m-6">
  <h2 class="text-center">
    Find the best craftmen for your construction or restoration works
  </h2>

  <div class="row text-center">
    <div class="col-12 col-md-6 col-lg-3 p-2">
      Secure payment &#10004
    </div>
    <div class="col-12 col-md-6 col-lg-3 p-2">
      Trusted and reliable artisans &#10004
    </div>
    <div class="col-12 col-md-6 col-lg-3 p-2">
      Customer care &#10004
    </div>
    <div class="col-12 col-md-6 col-lg-3 p-2">
      Fixed & Reliable quotations &#10004
    </div>
  </div>

<div class="container-fluid">
  <h2 class="text-center">
  <br>
Last booked skills :


<div class="container-fluid">
  <div class="content d-flex space-between">
      <div class="row">
          <div class="col-12 col-md-6 col-lg-3 p-2">
              <%= image_tag "https://res.cloudinary.com/dvateiuot/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1610626349/Artisan_HomePage_v2_ewfoyp.jpg", width: 360, height: 300, crop: :fill %>
          </div>
          <div class="col-12 col-md-6 col-lg-3 p-2">
              <%= image_tag "https://res.cloudinary.com/dvateiuot/image/upload/v1610626349/HomePage_v6_p1la1c.jpg", width: 360, height: 300, crop: :fill %>
          </div>
          <div class="col-12 col-md-6 col-lg-3 p-2">
              <%= image_tag "https://res.cloudinary.com/dvateiuot/image/upload/v1610626349/Artisan_HomePage_v4_bwyqao.jpg", width: 360, height: 300, crop: :fill %>
          </div>
          <div class="col-12 col-md-6 col-lg-3 p-2">
              <%= image_tag "https://res.cloudinary.com/dvateiuot/image/upload/v1610626349/HomePage_v7_wgufsy.jpg", width: 360, height: 300, crop: :fill %>
          </div>
          <div class="col-12 col-md-6 col-lg-3 p-2">
              <%= image_tag "https://res.cloudinary.com/dvateiuot/image/upload/v1610626349/HomePage_v8_p9rdd4.jpg", width: 360, height: 300, crop: :fill %>
          </div>
          <div class="col-12 col-md-6 col-lg-3 p-2">
              <%= image_tag "https://res.cloudinary.com/dvateiuot/image/upload/v1610626349/HomePage_v10_ojayq5.jpg", width: 360, height: 300, crop: :fill %>
          </div>
          <div class="col-12 col-md-6 col-lg-3 p-2">
              <%= image_tag "https://res.cloudinary.com/dvateiuot/image/upload/v1610626349/HomePage_v9_sqshbw.jpg", width: 360, height: 300, crop: :fill %>
          </div>
          <div class="col-12 col-md-6 col-lg-3 p-2">
              <%= image_tag "https://res.cloudinary.com/dvateiuot/image/upload/v1610626349/HomePage_v10_ojayq5.jpg", width: 360, height: 300, crop: :fill %>
          </div>
      </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/dvateiuot/image/upload/v1610807132/logo_mgtbjl.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Add a skill", new_skill_path, class: "nav-link" %>
        </li>
         <li class="nav-item">
          <%= link_to "Browse skills", skills_path, class: "nav-link" %>

        </li>

        <li class="nav-item">
          <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://res.cloudinary.com/dvateiuot/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_red,b_rgb:262c35/v1610806933/Donald_faf4wu.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Edit profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "All skills", skills_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Inscription",new_user_registration_path, class: "nav-link" %>
        </li>
        <!-- <li class="nav-item"> -->

          <%= link_to "Connexion", new_user_session_path, class: "btn-ghost" %>
        <!-- </li> -->

      <% end %>
    </ul>
  </div>
</div>

app/views/skills/index.html.erb
<div class="container justify-content-center">
  <h1 class="">Skills Index</h1>

  <div class="d-flex align-items flex-wrap">

  <% @skills.each do |skill|%>
    <div class="card d-flex align-items m-3" style="width: 18rem">
      <%= cl_image_tag(skill.photo.key, class: "card-img-top", width: 400, :aspect_ratio=>"4:3", :crop=>"fill") %>
      <div class="card-body d-flex align-items">
        <p class="card-title "> <%= skill.name%> </p>
      </div>
      <a href="<%=skill_path(skill)%>" class="btn btn-primary">See more details</a>
    </div>
    <%end%>
  </div>
</div>

app/views/skills/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h1>Add your new skill</h1>
  </div>
  <div class="row justify-content-center">
    <%= simple_form_for @skill do |f| %>
      <%= f.input :name %>
      <%= f.input :unit_price %>
      <%= f.input :description %>
      <%= f.input :photo, as: :file %>
      <div class="row justify-content-center">
        <%= f.button :submit, 'Create Skill', class:'btn btn-ghost'  %>
      </div>
    <% end %>
  </div>

</div>

app/views/skills/show.html.erb
<div class="container">
  <div class="row text-center d-flex justify-content-between", style="width:700px, margin: 0 auto, background:white">
    <div class="image" style="padding: 0px">
      <%= cl_image_tag @skill.photo.key, width: 400, :aspect_ratio=>"4:3", :crop=>"fill" %>
    </div>   
    <div class="description", style="display: flex; align-items: center; justify-content: center; padding: 30px; flex-grow:1">
      <div>
        <h1><%= @skill.name %></h1>
        <h2><%= @skill.unit_price %>€ per day</h2>
        <p><%=@skill.description%></p>
        <% if @skill.user == current_user%>
          <%= link_to "Go to your dashboard", dashboard_path(@skill), class: "btn btn-primary" %>
        <% else %>
          <%= link_to "Book", new_skill_booking_path(@skill), class: "btn btn-primary" %>
        <% end %>
      </div>
  </div>    
  </div>
</div>